### ISSUE TITLE
Unhandled Exception Occured with : KeyError: 'English_United States'

### ISSUE THREAD

**Issue by kapilsoni2013** [HenestrosaConH/audiotext#1]
When I ran the "audiotext.exe" exe file from the audiotext-v1.2.0.zip after extraction. I got the below exception.

`Traceback (most recent call last):
  File "main.py", line 261, in <module>
  File "main.py", line 19, in __init__
  File "main.py", line 62, in create_sidebar
KeyError: 'English_United States'
`
![image](https://user-images.githubusercontent.com/29603970/218092117-6b184432-cfa9-4022-a174-6bc629a7e644.png)

**Comment by altwitt** [comment]
kapilsoni2013's exception happened to me as well

**Comment by HenestrosaConH** [comment]
Hi. Thank you all for the feedback. I'm currently working to fix this issue.

**Comment by HenestrosaConH** [comment]
I've just released [version 1.2.1](https://github.com/HenestrosaConH/audiotext/releases/tag/v1.2.1) fixing this bug. Please, check it out and let me know if everything works as expected. 
Thank you.

**Comment by ahuyenta** [comment]
> I've just released [version 1.2.1](https://github.com/HenestrosaConH/audiotext/releases/tag/v1.2.1) fixing this bug. Please, check it out and let me know if everything works as expected. Thank you.

![image](https://user-images.githubusercontent.com/89607123/222303607-1ce04c3e-5e9a-4175-b6fa-d145668dab1c.png)

1.2.1
