### ISSUE TITLE
Asking a Question.

### ISSUE THREAD

**Issue by mahfujul-alam-anik** [HenestrosaConH/audiotext#2]
Can I use more than 10 minutes of audio to translate to text? And is it free or not? Do I have to buy google API? Thanks.

**Comment by HenestrosaConH** [comment]
Hi.

I haven't set an API key for the project, so if you use the program, you would be using the Google Speech-To-Text API free tier, which can transcribe up to 60 minutes of audio per month at no cost. Beyond that, you will need to generate an API key. The pricing is based on the number of audio minutes transcribed, and there are different rates depending on the type of audio and the service level you choose.

I'm going to update the README.md to include this information as I think that it's an important aspect to consider.

Hopefully, this answers your question. Feel free to ask anything else that you have in mind :)

**Comment by HenestrosaConH** [comment]
Hi again!

I'm going to change the speech_recognition package to [whisper](https://github.com/openai/whisper), which will allow the users to transcribe audio unlimitedly offline! I think it's a huge improve over the current integration of speech_recognition package. However, I've yet to make the necessary changes to make this possible.

**Comment by mahfujul-alam-anik** [comment]
Thanks for your reply and focus.
