### ISSUE TITLE
Program doesn't start on Windows 10 with KeyError de_DE[Bug] 

### ISSUE THREAD

**Issue by TestAccount129** [HenestrosaConH/audiotext#5]
Executing the release v1.2.1-windows gives me the following error.  
I don't know what my location code has to do with keeping the program from successfully starting.
```
Traceback (most recent call last):
  File "app.py", line 46, in <module>
  File "app.py", line 32, in __init__
  File "view\main_window.py", line 17, in __init__
  File "view\main_window.py", line 58, in _init_sidebar
KeyError: 'de_DE'
```

**Comment by HenestrosaConH** [comment]
Hi.

The location code is used to change the language of the application according to your system language. Let me take a look at it and I'll come back as soon as I fix it.

**Comment by HenestrosaConH** [comment]
Hello again.

Could you please download the [v1.2.3](https://github.com/HenestrosaConH/audiotext/releases/tag/v1.2.3) release? The issue should be fixed now.

**Comment by TestAccount129** [comment]
It starts now, issue is solved. 
However transcription does not work for any of the sound files I load in. Well, that's a different issue.

**Comment by HenestrosaConH** [comment]
Could you please create a new issue providing more details? I'll close this issue for now because it seems to be solved now.
