### ISSUE TITLE
[Bug] audiotext-v1.2.3

### ISSUE THREAD

**Issue by SWxEng** [HenestrosaConH/audiotext#8]
hi @HenestrosaConH 

What is this ?....Virus !

virustotal
.
audiotext.exe
https://www.virustotal.com/gui/file/ddcd3610bb927141e1744e93566220f12c3ae7a1260589c50dd9831d50fca595
.
audiotext-v1.2.3-windows.zip
https://www.virustotal.com/gui/file/a97156df8c0bdaa35e78a104bad13347ca71cb6aea1d079afbae458be650ed07

**Comment by HenestrosaConH** [comment]
Hello.

Those are false negatives. I encourage you to run more anti-malware software such as Malwarebytes and BitDefender on both files to verify that no virus is detected. Both the `.exe` and `.zip` files have been built from the source code in this repository. I encourage you to thoroughly inspect the code on your own and make your own educated answer, along with generating both files and sending both to VirusTotal to check that these false positives will also occur.

In addition, the information provided by the false positives is so small that it's not possible to find out what the cause of the false positive might be. Each false positive provides different reasons, which doesn't lead to a consistent verdict. This program doesn't ask for administrator privileges, nor does it perform tasks that are not related to reading and writing the file that the user selects for transcription. It doesn't send information to remote sites other than the Google API when the "Transcribe" button is clicked.

Also, it might be useful to investigate more about false positives on VirusTotal and understand that it uses inaccurate AI anti-malware tools, such as Sangfor Engine Zero, that return false positives **quite** often See [this thread](https://forum.fxsound.com/t/virustotal-com-says-it-has-a-virus/1692) for more information.

Regards.

**Comment by SWxEng** [comment]
Thank you
